# Generated by Django 3.2.16 on 2022-12-16 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='created_date',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 16, 20, 50, 49, 94527, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
