# Generated by Django 3.2.16 on 2022-12-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='full_name',
            new_name='name',
        ),
    ]
